/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Imagen;
import com.sv.udb.clases.Registro;
import com.sv.udb.clases.Tanques;
import com.sv.udb.clases.ventas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author bernardo
 */
public class frmPetrolito extends javax.swing.JFrame {

    /**
     * Creates new form frmPetrolito
     */
    List<Tanques> lstTanq;
    List<Registro> lstRegi;
    Timer timer[];
    double text[];
    double cont[];
    public frmPetrolito() {
        initComponents();
        this.setLocationRelativeTo(null);
        Imagen img = new Imagen("com/sv/udb/images/diesel.png");
        pnlDiesel.add(img);
        pnlDiesel.repaint();
        Imagen img2 = new Imagen("com/sv/udb/images/regular.png");
        pnlRegular.add(img2);
        pnlRegular.repaint();
        Imagen img3 = new Imagen("com/sv/udb/images/especial.png");
        pnlEspecial.add(img3);
        pnlEspecial.repaint();
        this.poblardata();
        cont = new double[3];
        cont[0] = 0;
        cont[1] = 0;
        cont[2] = 0;
        timer = new Timer[3];
        text = new double[3];
        this.calcularPor();
        this.timer[0] = new Timer (10, new ActionListener ()
        {
            public void actionPerformed(ActionEvent e)
            {   
                Timer(0, lblPorD);
            }
        });
        this.timer[0].start();
        
        this.timer[1] = new Timer (10, new ActionListener ()
        {
            public void actionPerformed(ActionEvent e)
            {   
                Timer(1, lblPorR);
            }
        });
        this.timer[1].start();
        
        this.timer[2] = new Timer (10, new ActionListener ()
        {
            public void actionPerformed(ActionEvent e)
            {
                Timer(2, lblPorE);
            }
        });
        this.timer[2].start();
    }
    
    private void poblardata() {
        ventas obje = new ventas();
        this.lstTanq = new ArrayList<>();
        this.lstTanq = obje.getDataTanques();
        this.lstRegi = new ArrayList<>();
        this.lstRegi = obje.getDataRegistros();
    }
    
    private void Timer(int indice, JLabel lbl)
    {
        if (cont[indice] <= text[indice])
                {
                    if (cont[indice] >= text[indice]-1)
                    {
                        cont[indice] = cont[indice] + 0.01;
                        DecimalFormat formateador = new DecimalFormat("###.##");
                        lbl.setText(formateador.format(cont[indice])+"%");
                        lbl.setText(formateador.format(text[indice])+"%");
                        if (cont[indice]-text[indice] == 0)
                        {
                            
                            timer[indice].stop();
                        }
                    }
                    else
                    {
                        DecimalFormat formateador = new DecimalFormat("###.##");
                        lbl.setText(formateador.format(cont[indice])+"%");
                        cont[indice] = cont[indice] + 1;
                    }
                }
    }
    
   private void calcularPor() {
       double maxD = Double.parseDouble(this.lstTanq.get(0).getMaximo());
       double maxR = Double.parseDouble(this.lstTanq.get(1).getMaximo());
       double maxE = Double.parseDouble(this.lstTanq.get(2).getMaximo());
       double actD = Double.parseDouble(this.lstTanq.get(0).getActual());
       double actR = Double.parseDouble(this.lstTanq.get(1).getActual());
       double actE = Double.parseDouble(this.lstTanq.get(2).getActual());
       DecimalFormat formateador = new DecimalFormat("###.##");
       text[0] = Double.parseDouble(formateador.format(100 - (maxD - actD)/10));
       text[1] = Double.parseDouble(formateador.format(100 - (maxR - actR)/10));
       text[2] = Double.parseDouble(formateador.format(100 - (maxE - actE)/10));
       /*this.lblPorD.setText(formateador.format((100 - (maxD - actD)/10))+"%");
       this.lblPorR.setText(formateador.format((100 - (maxR - actR)/10))+"%");
       this.lblPorE.setText(formateador.format((100 - (maxE - actE)/10))+"%");*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlDiesel = new javax.swing.JPanel();
        lblPorD = new javax.swing.JLabel();
        pnlRegular = new javax.swing.JPanel();
        lblPorR = new javax.swing.JLabel();
        pnlEspecial = new javax.swing.JPanel();
        lblPorE = new javax.swing.JLabel();
        pnlCompra = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbGaso = new javax.swing.JComboBox<>();
        rdGalo = new javax.swing.JRadioButton();
        rdDin = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIngre = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        txtAgreD = new javax.swing.JTextField();
        txtAgreR = new javax.swing.JTextField();
        txtAgreE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTanques = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "El petrolito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harlow Solid Italic", 0, 36))); // NOI18N

        pnlDiesel.setBorder(javax.swing.BorderFactory.createTitledBorder("Diesel"));
        pnlDiesel.setPreferredSize(new java.awt.Dimension(180, 170));

        lblPorD.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblPorD.setText("100%");

        javax.swing.GroupLayout pnlDieselLayout = new javax.swing.GroupLayout(pnlDiesel);
        pnlDiesel.setLayout(pnlDieselLayout);
        pnlDieselLayout.setHorizontalGroup(
            pnlDieselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDieselLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblPorD)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pnlDieselLayout.setVerticalGroup(
            pnlDieselLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDieselLayout.createSequentialGroup()
                .addComponent(lblPorD)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        pnlRegular.setBorder(javax.swing.BorderFactory.createTitledBorder("Regular"));
        pnlRegular.setPreferredSize(new java.awt.Dimension(180, 170));

        lblPorR.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblPorR.setText("100%");

        javax.swing.GroupLayout pnlRegularLayout = new javax.swing.GroupLayout(pnlRegular);
        pnlRegular.setLayout(pnlRegularLayout);
        pnlRegularLayout.setHorizontalGroup(
            pnlRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegularLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(lblPorR)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        pnlRegularLayout.setVerticalGroup(
            pnlRegularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegularLayout.createSequentialGroup()
                .addComponent(lblPorR)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        pnlEspecial.setBorder(javax.swing.BorderFactory.createTitledBorder("Especial"));
        pnlEspecial.setPreferredSize(new java.awt.Dimension(180, 170));

        lblPorE.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblPorE.setText("100%");

        javax.swing.GroupLayout pnlEspecialLayout = new javax.swing.GroupLayout(pnlEspecial);
        pnlEspecial.setLayout(pnlEspecialLayout);
        pnlEspecialLayout.setHorizontalGroup(
            pnlEspecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblPorE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlEspecialLayout.setVerticalGroup(
            pnlEspecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialLayout.createSequentialGroup()
                .addComponent(lblPorE)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        pnlCompra.setBackground(new java.awt.Color(255, 204, 204));
        pnlCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Realizar compra"));
        pnlCompra.setForeground(new java.awt.Color(255, 255, 255));

        lblCliente.setText("Cliente:");

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Gasolina:");

        cmbGaso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Diesel", "Regular", "Especial" }));

        buttonGroup1.add(rdGalo);
        rdGalo.setText("Por galones");
        rdGalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGaloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdDin);
        rdDin.setText("Por dinero");

        jLabel5.setText("Seleccione el tipo de compra:");

        jLabel6.setText("Ingrese:");

        txtIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngreActionPerformed(evt);
            }
        });
        txtIngre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIngreKeyPressed(evt);
            }
        });

        btnPagar.setText("Realizar compra");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCompraLayout = new javax.swing.GroupLayout(pnlCompra);
        pnlCompra.setLayout(pnlCompraLayout);
        pnlCompraLayout.setHorizontalGroup(
            pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCliente)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCliente)
                            .addComponent(cmbGaso, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addComponent(rdGalo)
                        .addGap(18, 18, 18)
                        .addComponent(rdDin))
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIngre)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(pnlCompraLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnPagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCompraLayout.setVerticalGroup(
            pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdGalo)
                    .addComponent(rdDin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtIngre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnPagar)
                .addContainerGap())
        );

        btnGenerar.setText("Ver ventas");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtAgreD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgreDKeyPressed(evt);
            }
        });

        txtAgreR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgreRKeyPressed(evt);
            }
        });

        txtAgreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgreEKeyPressed(evt);
            }
        });

        jLabel1.setText("*Para agregar galones inserte la cantidad y presione enter.");

        btnTanques.setText("Ver combustible vendido");
        btnTanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanquesActionPerformed(evt);
            }
        });

        jLabel2.setText("*Si se ingresan mas de 2 decimales se aproximaran.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnGenerar)
                            .addGap(18, 18, 18)
                            .addComponent(btnTanques))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAgreD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlRegular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAgreR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAgreE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnlEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlRegular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerar)
                            .addComponent(btnTanques))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        txtCliente.setText("");
        txtIngre.setText("");
        cmbGaso.setSelectedIndex(0);
        rdDin.setSelected(false);
        rdGalo.setSelected(false);
    }
    
    private void actualizar(int indice) {
        ventas obj = new ventas();
        obj.ActualizarRegistro(lstRegi);
        obj.ActualizarTanques(lstTanq);
        calcularPor();
        this.cont[indice] = 0;
        this.timer[indice].start();
        limpiar();
    }
    
    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void rdGaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGaloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdGaloActionPerformed

    private void txtIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngreActionPerformed

    private String fechaSist() {
        Calendar c1 = new GregorianCalendar();
        String dia, mes, anio;
        dia = String.valueOf(c1.get(Calendar.DATE));
        mes =  String.valueOf(c1.get(Calendar.MONTH));
        anio = String.valueOf(c1.get(Calendar.YEAR));
        if (dia.length() == 1){
            dia = "0"+dia;
        }
        if (mes.length() == 1){
            mes = "0"+mes;
        }
            String fecha = dia + "/" + mes + "/" + anio;
            return fecha;
    }
    
    private void AgregarTanq(double cant, int indice) {
        double nuevo = Double.parseDouble(this.lstTanq.get(indice).getActual()) + cant;
        if (nuevo <= 1000)
        {
            DecimalFormat formateador = new DecimalFormat("###.##");
            this.lstTanq.get(indice).setActual(formateador.format(nuevo));
            ventas obj = new ventas();
            obj.ActualizarTanques(this.lstTanq);
            calcularPor();
            this.cont[indice] = 0;
            this.timer[indice].start();
            JOptionPane.showMessageDialog(this, "Cantidad agregada correctamente!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El total de galones excede la capacidad del tanque!");
        }
    }
    
    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        if (!txtCliente.getText().isEmpty() && cmbGaso.getSelectedIndex() > 0 && !txtIngre.getText().isEmpty())
        {
            try {
                double ingre = Double.parseDouble(txtIngre.getText());
            if (rdGalo.isSelected()){
                double total = ingre * Double.parseDouble(this.lstTanq.get(cmbGaso.getSelectedIndex()-1).getPrecio());
                if ((Double.parseDouble(this.lstTanq.get(cmbGaso.getSelectedIndex()-1).getActual()) - ingre) > 0){
                    DecimalFormat formateador = new DecimalFormat("###.##");
                    JOptionPane.showMessageDialog(this, "El total a pagar es: $" +formateador.format(total));
                    Registro obj = new Registro(txtCliente.getText(), formateador.format(ingre), formateador.format(total), cmbGaso.getSelectedItem().toString(), fechaSist());
                    this.lstRegi.add(obj);
                    this.lstTanq.get(cmbGaso.getSelectedIndex()-1).setActual(formateador.format((Double.parseDouble(this.lstTanq.get(cmbGaso.getSelectedIndex()-1).getActual())) - ingre));
                    actualizar(cmbGaso.getSelectedIndex()-1);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Lo sentimos pero los galones del tanque son insuficientes para la transacción");
                }
                
            }
            else if (rdDin.isSelected())
            {
                double total = ingre / Double.parseDouble(this.lstTanq.get(cmbGaso.getSelectedIndex()-1).getPrecio());
                if ((Double.parseDouble(this.lstTanq.get(cmbGaso.getSelectedIndex()-1).getActual()) - total) > 0) {
                    DecimalFormat formateador = new DecimalFormat("###.##");
                    JOptionPane.showMessageDialog(this, "Total de galones: " +formateador.format(total));
                    Registro obj = new Registro(txtCliente.getText(), formateador.format(total), formateador.format(ingre), cmbGaso.getSelectedItem().toString(), fechaSist());
                    this.lstRegi.add(obj);
                    this.lstTanq.get(cmbGaso.getSelectedIndex()-1).setActual(formateador.format((Double.parseDouble(this.lstTanq.get(cmbGaso.getSelectedIndex()-1).getActual())) - total));
                    actualizar(cmbGaso.getSelectedIndex()-1);
                }
                else 
                {
                    JOptionPane.showMessageDialog(this, "Lo sentimos pero los galones del tanque son insuficientes para la transacción");
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "por favor seleccione un tipo de pago.");
            }
            
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Por favor solamente ingresa datos validos (números positivos).");
            }
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        frmVentas frmVent = new frmVentas();
        frmVent.setVisible(true);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void txtAgreDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgreDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (!txtAgreD.getText().isEmpty())
            {
                double ingre = Double.parseDouble(txtAgreD.getText());
                this.AgregarTanq(ingre, 0);
                this.txtAgreD.setText("");
            }
        }
    }//GEN-LAST:event_txtAgreDKeyPressed

    private void txtAgreRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgreRKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (!txtAgreR.getText().isEmpty())
            {
                double ingre = Double.parseDouble(txtAgreR.getText());
                this.AgregarTanq(ingre, 1);
                this.txtAgreR.setText("");
            }
        }
    }//GEN-LAST:event_txtAgreRKeyPressed

    private void txtAgreEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgreEKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (!txtAgreE.getText().isEmpty())
            {
                double ingre = Double.parseDouble(txtAgreE.getText());
                this.AgregarTanq(ingre, 2);
                this.txtAgreE.setText("");
            }
        }
    }//GEN-LAST:event_txtAgreEKeyPressed

    private void btnTanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanquesActionPerformed
        // TODO add your handling code here:
        double cant[] = new double[3];
        for (Registro temp : this.lstRegi)
        {
            if (temp.getFecha().equals(fechaSist()))
            {
                switch (temp.getTipo()){
                    case "Diesel":
                        cant[0] = cant[0] + Double.parseDouble(temp.getCantidad());
                        break;
                    case "Regular":
                        cant[1] = cant[1] + Double.parseDouble(temp.getCantidad());
                        break;
                    case "Especial":
                        cant[2] = cant[2] + Double.parseDouble(temp.getCantidad());
                        break;
                }
                        
            }
        }
        JOptionPane.showMessageDialog(this, "Total de combustible vendido hoy. \n"
                + "Diesel: " + cant[0] + "\n"
                        + "Regular: " + cant[1] + "\n"
                                + "Especial: " + cant[2] );
    }//GEN-LAST:event_btnTanquesActionPerformed

    private void solonumeros(KeyEvent e) {
    char caracter = e.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
}
    
    
    private void txtIngreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngreKeyPressed
        // TODO add your handling code here:
        this.solonumeros(evt);
    }//GEN-LAST:event_txtIngreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPetrolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPetrolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPetrolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPetrolito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPetrolito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnTanques;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbGaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblPorD;
    private javax.swing.JLabel lblPorE;
    private javax.swing.JLabel lblPorR;
    private javax.swing.JPanel pnlCompra;
    private javax.swing.JPanel pnlDiesel;
    private javax.swing.JPanel pnlEspecial;
    private javax.swing.JPanel pnlRegular;
    private javax.swing.JRadioButton rdDin;
    private javax.swing.JRadioButton rdGalo;
    private javax.swing.JTextField txtAgreD;
    private javax.swing.JTextField txtAgreE;
    private javax.swing.JTextField txtAgreR;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtIngre;
    // End of variables declaration//GEN-END:variables
}
